# Generated by Django 5.2.1 on 2025-08-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_customuser_mobile_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_arrival',
            field=models.BooleanField(default=False),
        ),
    ]
