# Generated by Django 5.2.1 on 2025-08-01 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_is_arrival'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='base_price',
        ),
    ]
